### ISSUE TITLE
register hangs after re-printing receipt or voiding transaction

### ISSUE THREAD

**Issue by slucy** [openproduce/marzipan#16]
1. press F9 to review transactions
2. select a transaction
3. re-print receipt
4. press ESC to return to main interface
5. try typing.  there is a 10-30 second hang.
6. press enter to add item.  a second hang occurs.
7. after this POS is back to normal

**Comment by jeredw** [comment]
By default, SQLAlchemy expires all ORM state after each "commit" operation so that subsequent queries see the correct database state:
http://docs.sqlalchemy.org/en/latest/orm/session_api.html#sqlalchemy.orm.session.Session.commit

The review transactions dialog does a commit, so that invalidates all stored references to items in the index for ItemSearchDialog. Then an unsuspecting for loop over items causes SQLAlchemy to reload each item one at a time, and hilarity ensues.

A safe workaround here is to "reindex" after each commit. A more nuanced fix would be to turn off the auto-expire stuff, and more precisely expire only the right state after commit, but that seems a little bit heavy-handed here.
